// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS6-ML2j7CJ1TFSDmuO5Mn72JKXdXQUGg',
    appId: '1:619698794413:web:30f6f02cd7dcbeaa6d3b24',
    messagingSenderId: '619698794413',
    projectId: 'talktime-4e96f',
    authDomain: 'talktime-4e96f.firebaseapp.com',
    storageBucket: 'talktime-4e96f.appspot.com',
    measurementId: 'G-7YBY1QHQXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAop4pKtSzo-_TkUzOB8dHJ2INyxp_6i28',
    appId: '1:619698794413:android:3721fed9494fbfb66d3b24',
    messagingSenderId: '619698794413',
    projectId: 'talktime-4e96f',
    storageBucket: 'talktime-4e96f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNyGbgfgfUiTE7YDrIO6swq1X38zLmOFc',
    appId: '1:619698794413:ios:23c4f7d841f36e346d3b24',
    messagingSenderId: '619698794413',
    projectId: 'talktime-4e96f',
    storageBucket: 'talktime-4e96f.appspot.com',
    iosBundleId: 'com.example.talktime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNyGbgfgfUiTE7YDrIO6swq1X38zLmOFc',
    appId: '1:619698794413:ios:23c4f7d841f36e346d3b24',
    messagingSenderId: '619698794413',
    projectId: 'talktime-4e96f',
    storageBucket: 'talktime-4e96f.appspot.com',
    iosBundleId: 'com.example.talktime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS6-ML2j7CJ1TFSDmuO5Mn72JKXdXQUGg',
    appId: '1:619698794413:web:16a84274297849686d3b24',
    messagingSenderId: '619698794413',
    projectId: 'talktime-4e96f',
    authDomain: 'talktime-4e96f.firebaseapp.com',
    storageBucket: 'talktime-4e96f.appspot.com',
    measurementId: 'G-V3SM3H92YV',
  );

}